export const FETCH_WEATHER_REQUEST = 'FETCH_WEATHER_REQUEST';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';

export const FETCH_GEO_WEATHER_REQUEST = 'FETCH_GEO_WEATHER_REQUEST';
export const FETCH_GEO_WEATHER_SUCCESS = 'FETCH_GEO_WEATHER_SUCCESS';
export const FETCH_GEO_WEATHER_FAILURE = 'FETCH_GEO_WEATHER_FAILURE';

export const ADD_TO_FAVOURITES_REQUEST = 'ADD_TO_FAVOURITES_REQUEST';
export const ADD_TO_FAVOURITES_SUCCESS = 'ADD_TO_FAVOURITES_SUCCESS';
export const ADD_TO_FAVOURITES_FAILURE = 'ADD_TO_FAVOURITES_FAILURE';

export const REMOVE_FROM_FAVOURITES_REQUEST = 'REMOVE_FROM_FAVOURITES_REQUEST';
export const REMOVE_FROM_FAVOURITES_SUCCESS = 'REMOVE_FROM_FAVOURITES_SUCCESS';
export const REMOVE_FROM_FAVOURITES_FAILURE = 'REMOVE_FROM_FAVOURITES_FAILURE';

export const REMOVE_FROM_DEFAULT_REQUEST = 'REMOVE_FROM_DEFAULT_REQUEST';
export const REMOVE_FROM_DEFAULT_SUCCESS = 'REMOVE_FROM_DEFAULT_SUCCESS';
export const REMOVE_FROM_DEFAULT_FAILURE = 'REMOVE_FROM_DEFAULT_FAILURE';

export const ADD_OR_UPDATE_COMMENT_REQUEST = 'ADD_OR_UPDATE_COMMENT_REQUEST';
export const ADD_OR_UPDATE_COMMENT_SUCCESS = 'ADD_OR_UPDATE_COMMENT_SUCCESS';
export const ADD_OR_UPDATE_COMMENT_FAILURE = 'ADD_OR_UPDATE_COMMENT_FAILURE';

export const REMOVE_COMMENT_REQUEST = 'REMOVE_COMMENT_REQUEST';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';
export const REMOVE_COMMENT_FAILURE = 'REMOVE_COMMENT_FAILURE';
