export const FETCH_WEATHER_REQUEST = 'FETCH_WEATHER_REQUEST';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_CURRENT_FAILURE = 'FETCH_CURRENT_FAILURE';

export const FETCH_GEO_WEATHER_REQUEST = 'FETCH_GEO_WEATHER_REQUEST';
export const FETCH_GEO_WEATHER_SUCCESS = 'FETCH_GEO_WEATHER_SUCCESS';
export const FETCH_GEO_WEATHER_FAILURE = 'FETCH_GEO_WEATHER_FAILURE';

export const ADD_TO_FAVOURITES_REQUEST = 'ADD_TO_FAVOURITES_REQUEST';
export const ADD_TO_FAVOURITES_SUCCESS = 'ADD_TO_FAVOURITES_SUCCESS';
export const ADD_TO_FAVOURITES_FAILURE = 'ADD_TO_FAVOURITES_FAILURE';

export const REMOVE_FROM_FAVOURITES_REQUEST = 'REMOVE_FROM_FAVOURITES_REQUEST';
export const REMOVE_FROM_FAVOURITES_SUCCESS = 'REMOVE_FROM_FAVOURITES_SUCCESS';
export const REMOVE_FROM_FAVOURITES_FAILURE = 'REMOVE_FROM_FAVOURITES_FAILURE';
